package content

import (
	"strings"
	"testing"
)

func render(t *testing.T, src string, resolve MentionResolver) string {
	t.Helper()
	return RenderHTML(Parse(src, resolve))
}

func wants(t *testing.T, got string, subs ...string) {
	t.Helper()
	for _, s := range subs {
		if !strings.Contains(got, s) {
			t.Fatalf("output missing %q:\n%s", s, got)
		}
	}
}

func rejects(t *testing.T, got string, subs ...string) {
	t.Helper()
	for _, s := range subs {
		if strings.Contains(got, s) {
			t.Fatalf("output must not contain %q:\n%s", s, got)
		}
	}
}

func TestCommonMarkAndGFM(t *testing.T) {
	wants(t, render(t, "**bold** *em* ~~gone~~ `code`", nil),
		"<strong>bold</strong>", "<em>em</em>", "<del>gone</del>", "<code>code</code>")
	wants(t, render(t, "# Title\n\n> quoted", nil),
		"<h1>Title</h1>", "<blockquote><p>quoted</p></blockquote>")
	wants(t, render(t, "- a\n- b", nil), "<ul><li><p>a</p></li><li><p>b</p></li></ul>")
	wants(t, render(t, "3. c", nil), `<ol start="3">`)
	wants(t, render(t, "- [x] done\n- [ ] todo", nil),
		`<input type="checkbox" checked disabled>`, `<input type="checkbox" disabled>`)
	wants(t, render(t, "```go\nx := 1\n```", nil),
		`<pre><code class="language-go">x := 1`)
	wants(t, render(t, "| a | b |\n|---|---|\n| 1 | 2 |", nil),
		"<table>", "<th>a</th>", "<td>1</td>")
	wants(t, render(t, "see https://weft.example/x", nil),
		`<a href="https://weft.example/x" rel="noopener noreferrer" target="_blank">`)
	wants(t, render(t, "[label](https://ok.example)", nil),
		`<a href="https://ok.example"`, ">label</a>")
	// Chat semantics: a newline is a hard break.
	wants(t, render(t, "line one\nline two", nil), "line one<br>", "line two")
}

func TestXSSNeutralized(t *testing.T) {
	cases := []string{
		`<script>alert(1)</script>`,
		`hello <img src=x onerror=alert(1)>`,
		`[click](javascript:alert(1))`,
		`[click](JaVaScRiPt:alert(1))`,
		`[click](data:text/html;base64,xxx)`,
		"<iframe src='https://evil.example'></iframe>",
		`<a href="https://ok.example" onclick="steal()">x</a>`,
		"``` \n</textarea><script>1</script>\n```",
		`![x](javascript:alert(1))`,
	}
	for _, src := range cases {
		got := render(t, src, nil)
		// Hostile input may survive as ESCAPED text (&lt;img …&gt;) — what
		// must never appear is an executable position: a real tag or a
		// dangerous href. All real tags in output are generated by us.
		rejects(t, got, "<script", "<img", "<iframe",
			`href="javascript`, `href="data:`, `" onclick=`)
	}
	// The hostile text survives as VISIBLE escaped text, not silently dropped.
	wants(t, render(t, `<script>alert(1)</script>`, nil), "&lt;script&gt;")
}

func TestMentions(t *testing.T) {
	resolve := func(label string) (int64, bool) {
		if label == "Alice Chen" {
			return 7, true
		}
		return 0, false
	}
	got := render(t, "ping @**Alice Chen** and @**Nobody**", resolve)
	wants(t, got,
		`<span class="mention" data-user-id="7">@Alice Chen</span>`,
		`<span class="mention mention-unresolved">@Nobody</span>`)

	doc := Parse("hi @**Alice Chen**", resolve)
	ids := doc.Mentions()
	if len(ids) != 1 || ids[0] != 7 {
		t.Fatalf("mentions = %v, want [7]", ids)
	}
	// Mention labels are escaped like everything else.
	rejects(t, render(t, "@**<b>x</b>**", nil), "<b>")
}

func TestEmojiAndFlags(t *testing.T) {
	wants(t, render(t, "ship it :rocket:", nil), "🚀", `title=":rocket:"`)
	// Unknown shortcodes stay literal text.
	wants(t, render(t, "meh :not_an_emoji_xyz:", nil), ":not_an_emoji_xyz:")

	if !Parse("see https://x.example", nil).HasLink() {
		t.Fatal("HasLink should detect autolinks")
	}
	if Parse("plain", nil).HasLink() {
		t.Fatal("HasLink false positive")
	}
}

func TestASTRoundTrip(t *testing.T) {
	doc := Parse("**hi** @**A** :fire:\n\n- item", nil)
	raw := doc.JSON()
	if len(raw) == 0 || raw[0] != '{' {
		t.Fatalf("bad ast json: %s", raw)
	}
	// Empty input still yields a renderable doc.
	if got := RenderHTML(Parse("", nil)); got != "<p></p>" {
		t.Fatalf("empty doc render = %q", got)
	}
}
